site_name: Gremlins
site_url: https://gremlins.dev
repo_url: https://github.com/go-gremlins/gremlins
edit_uri: edit/main/docs/docs
site_description: A mutation testing tool for Go.
copyright: Made with ❤️ by Gremlins contributors. <span xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></span>
repo_name: go-gremlins/gremlins
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  custom_dir: overrides
  language: en
  palette:
    primary: cyan
    accent: amber
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/go-gremlins
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/gogremlins/gremlins
      name: Docker
  version:
    provider: mike
  release:
    full_version: !ENV [GR_FULL_VERSION, 'X.Y.Z']
    short_version: !ENV [GR_SHORT_VERSION, 'X.Y']

nav:
  - Home: index.md
  - Install: install.md
  - Quick start: quick-start.md
  - Usage:
      - Commands:
          - usage/commands/index.md
          - Unleash:
            - usage/commands/unleash/index.md
            - usage/commands/unleash/workers.md
      - usage/configuration.md
      - Mutations:
          - usage/mutations/index.md
          - usage/mutations/arithmetic_base.md
          - usage/mutations/conditionals_boundary.md
          - usage/mutations/conditionals_negation.md
          - usage/mutations/increment_decrement.md
          - usage/mutations/invert_negatives.md
          - usage/mutations/invert_logical.md
          - usage/mutations/invert_loop.md
      - Continuous integration:
          - usage/ci/github-action.md
          - usage/ci/docker.md
  - Contributing: CONTRIBUTING.md

plugins:
  - macros
  - search

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
